// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rmsd
double rmsd(NumericMatrix X, NumericMatrix Y);
RcppExport SEXP PatchSearch_rmsd(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    __result = Rcpp::wrap(rmsd(X, Y));
    return __result;
END_RCPP
}
// devsub
NumericVector devsub(NumericMatrix X, IntegerVector I, NumericMatrix Y, IntegerVector J);
RcppExport SEXP PatchSearch_devsub(SEXP XSEXP, SEXP ISEXP, SEXP YSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type I(ISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type J(JSEXP);
    __result = Rcpp::wrap(devsub(X, I, Y, J));
    return __result;
END_RCPP
}
// getNeighborsc
IntegerVector getNeighborsc(IntegerVector C, IntegerMatrix V, NumericMatrix X, NumericMatrix Y, double thresh, int nbnei);
RcppExport SEXP PatchSearch_getNeighborsc(SEXP CSEXP, SEXP VSEXP, SEXP XSEXP, SEXP YSEXP, SEXP threshSEXP, SEXP nbneiSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type nbnei(nbneiSEXP);
    __result = Rcpp::wrap(getNeighborsc(C, V, X, Y, thresh, nbnei));
    return __result;
END_RCPP
}
// enrichloopc
IntegerVector enrichloopc(IntegerVector C, IntegerVector K, NumericMatrix X, NumericMatrix Y, double thresh);
RcppExport SEXP PatchSearch_enrichloopc(SEXP CSEXP, SEXP KSEXP, SEXP XSEXP, SEXP YSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    __result = Rcpp::wrap(enrichloopc(C, K, X, Y, thresh));
    return __result;
END_RCPP
}
// enrichc
IntegerVector enrichc(IntegerVector C, IntegerVector K, NumericMatrix X, NumericMatrix Y, double thresh);
RcppExport SEXP PatchSearch_enrichc(SEXP CSEXP, SEXP KSEXP, SEXP XSEXP, SEXP YSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    __result = Rcpp::wrap(enrichc(C, K, X, Y, thresh));
    return __result;
END_RCPP
}
// vertexc
IntegerMatrix vertexc(CharacterVector XProp, IntegerVector Xseq, CharacterVector YProp, IntegerVector Yseq, NumericMatrix S, double sthresh);
RcppExport SEXP PatchSearch_vertexc(SEXP XPropSEXP, SEXP XseqSEXP, SEXP YPropSEXP, SEXP YseqSEXP, SEXP SSEXP, SEXP sthreshSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type XProp(XPropSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Xseq(XseqSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type YProp(YPropSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Yseq(YseqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type sthresh(sthreshSEXP);
    __result = Rcpp::wrap(vertexc(XProp, Xseq, YProp, Yseq, S, sthresh));
    return __result;
END_RCPP
}
// buildGraphc
IntegerMatrix buildGraphc(NumericMatrix X, int N, NumericMatrix Y, int M, IntegerMatrix V, double thresh);
RcppExport SEXP PatchSearch_buildGraphc(SEXP XSEXP, SEXP NSEXP, SEXP YSEXP, SEXP MSEXP, SEXP VSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    __result = Rcpp::wrap(buildGraphc(X, N, Y, M, V, thresh));
    return __result;
END_RCPP
}
