// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rmsd
double rmsd(NumericMatrix X, NumericMatrix Y);
RcppExport SEXP patchsearch_rmsd(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(rmsd(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// devsub
NumericVector devsub(NumericMatrix X, IntegerVector I, NumericMatrix Y, IntegerVector J);
RcppExport SEXP patchsearch_devsub(SEXP XSEXP, SEXP ISEXP, SEXP YSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type I(ISEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(devsub(X, I, Y, J));
    return rcpp_result_gen;
END_RCPP
}
// getNeighborsc
IntegerVector getNeighborsc(IntegerVector C, IntegerMatrix V, NumericMatrix X, NumericMatrix Y, double thresh, int nbnei);
RcppExport SEXP patchsearch_getNeighborsc(SEXP CSEXP, SEXP VSEXP, SEXP XSEXP, SEXP YSEXP, SEXP threshSEXP, SEXP nbneiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type nbnei(nbneiSEXP);
    rcpp_result_gen = Rcpp::wrap(getNeighborsc(C, V, X, Y, thresh, nbnei));
    return rcpp_result_gen;
END_RCPP
}
// enrichloopc
IntegerVector enrichloopc(IntegerVector C, IntegerVector K, NumericMatrix X, NumericMatrix Y, double thresh);
RcppExport SEXP patchsearch_enrichloopc(SEXP CSEXP, SEXP KSEXP, SEXP XSEXP, SEXP YSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(enrichloopc(C, K, X, Y, thresh));
    return rcpp_result_gen;
END_RCPP
}
// vertexc
IntegerMatrix vertexc(CharacterVector XProp, IntegerVector Xseq, CharacterVector YProp, IntegerVector Yseq, NumericMatrix S, double sthresh);
RcppExport SEXP patchsearch_vertexc(SEXP XPropSEXP, SEXP XseqSEXP, SEXP YPropSEXP, SEXP YseqSEXP, SEXP SSEXP, SEXP sthreshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type XProp(XPropSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Xseq(XseqSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type YProp(YPropSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Yseq(YseqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type sthresh(sthreshSEXP);
    rcpp_result_gen = Rcpp::wrap(vertexc(XProp, Xseq, YProp, Yseq, S, sthresh));
    return rcpp_result_gen;
END_RCPP
}
// buildGraphc
IntegerMatrix buildGraphc(NumericMatrix X, NumericMatrix Y, IntegerMatrix V, IntegerVector localdegree, double thresh, double localthresh);
RcppExport SEXP patchsearch_buildGraphc(SEXP XSEXP, SEXP YSEXP, SEXP VSEXP, SEXP localdegreeSEXP, SEXP threshSEXP, SEXP localthreshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type localdegree(localdegreeSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< double >::type localthresh(localthreshSEXP);
    rcpp_result_gen = Rcpp::wrap(buildGraphc(X, Y, V, localdegree, thresh, localthresh));
    return rcpp_result_gen;
END_RCPP
}
