# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmsd <- function(X, Y) {
    .Call('PatchSearch_rmsd', PACKAGE = 'PatchSearch', X, Y)
}

devsub <- function(X, I, Y, J) {
    .Call('PatchSearch_devsub', PACKAGE = 'PatchSearch', X, I, Y, J)
}

getNeighborsc <- function(C, V, X, Y, thresh, nbnei) {
    .Call('PatchSearch_getNeighborsc', PACKAGE = 'PatchSearch', C, V, X, Y, thresh, nbnei)
}

enrichloopc <- function(C, K, X, Y, thresh) {
    .Call('PatchSearch_enrichloopc', PACKAGE = 'PatchSearch', C, K, X, Y, thresh)
}

enrichc <- function(C, K, X, Y, thresh) {
    .Call('PatchSearch_enrichc', PACKAGE = 'PatchSearch', C, K, X, Y, thresh)
}

vertexc <- function(XProp, Xseq, YProp, Yseq, S, sthresh) {
    .Call('PatchSearch_vertexc', PACKAGE = 'PatchSearch', XProp, Xseq, YProp, Yseq, S, sthresh)
}

buildGraphc <- function(X, N, Y, M, V, thresh) {
    .Call('PatchSearch_buildGraphc', PACKAGE = 'PatchSearch', X, N, Y, M, V, thresh)
}

