# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute RMSD between matrices of coordinates X and Y
#'
#' @param X matrix Nx3
#' @param Y matrix Nx3
#' @export
rmsd <- function(X, Y) {
    .Call('patchsearch_rmsd', PACKAGE = 'patchsearch', X, Y)
}

#' Compute deviation between matrices of coordinates X index I and Y index J
#'
#' @param X matrix Nx3
#' @param I vector M
#' @param Y matrix Nx3
#' @param J vector M
#' @export
devsub <- function(X, I, Y, J) {
    .Call('patchsearch_devsub', PACKAGE = 'patchsearch', X, I, Y, J)
}

#' Get set of neighbors that could be added to the clique C
#'
#' @param C
#' @param V
#' @param X
#' @param Y
#' @param thresh
#' @param nbnei
#' @export
getNeighborsc <- function(C, V, X, Y, thresh, nbnei) {
    .Call('patchsearch_getNeighborsc', PACKAGE = 'patchsearch', C, V, X, Y, thresh, nbnei)
}

#' enrich clique with neighbors
#'
#' @param C
#' @param K
#' @param X
#' @param Y
#' @param thresh
#' @export
enrichloopc <- function(C, K, X, Y, thresh) {
    .Call('patchsearch_enrichloopc', PACKAGE = 'patchsearch', C, K, X, Y, thresh)
}

#' Constructs vertex table V
#'
#' @param XProp
#' @param Xseq
#' @param YProp
#' @param Yseq
#' @param S
#' @param sthresh
#' @export
vertexc <- function(XProp, Xseq, YProp, Yseq, S, sthresh) {
    .Call('patchsearch_vertexc', PACKAGE = 'patchsearch', XProp, Xseq, YProp, Yseq, S, sthresh)
}

#' Constructs product graph
#'
#' @param X matrix Nx3
#' @param Y matrix Nx3
#' @param V matrix Nvx2
#' @export
buildGraphc <- function(X, Y, V, localdegree, thresh, localthresh) {
    .Call('patchsearch_buildGraphc', PACKAGE = 'patchsearch', X, Y, V, localdegree, thresh, localthresh)
}

